### PR TITLE
Connect to App to API

### PR DESCRIPTION
**Pull request by ifeanyi305**
These are the changes in the feature branch pull request:

Added functionality to fetch a list of books from an API on App load.
Added functionality to persist new book to API using Axios and createAsyncThunk
Added functionality to remove the book from API using Axios and createAsyncThunk

### CODE REVIEW

**Review by youmari — CHANGES_REQUESTED** [review]
Hi @ifeanyi305 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Great commit messages
✔️ PRO PR
✔️ No linter error 

## Required Changes ♻️

- [ ] it would be better if you make sure the `MIT` link in the readme file is working and add the MIT file in so that project will be pro

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ifeanyi305** [comment]
Thanks for your feedback.
I will implement the required changes to my project

**Review by OLIPLICHE — APPROVED** [review]
Hi @ifeanyi305, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Highlights
- Implemented the required changes👏 👏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ifeanyi305** [comment]
Thanks 💯  for the approval

**Pull request merged**
